export interface SignalResultRow {
  testName: string;
  periods: string;
  set: string;
  code: string;
  datasetType: string;
  consistency: string;
  verifySignal: string;
  magnitude: string;
  effectSize: string;
  passPercentage: string;
  totalTested: number;
  correctlyDefined: number;
  tradable: number;
  directionAccuracy: string;
  magnitudeAccuracy: string;
  strongTradable: number;
  moderateTradable: number;
  weakTradable: number;
}

export const SIGNAL_RESULTS: SignalResultRow[] = [
  // TEST 1 - PC_SC
  {
    testName: "TEST 1",
    periods: '["2024-04","2025-03"],["2025-04","2025-09"]',
    set: "PC_SC",
    code: "PC-SC-DC-M3-E02-PP67",
    datasetType: "PC",
    consistency: "SC",
    verifySignal: "DC",
    magnitude: "M3",
    effectSize: "E02",
    passPercentage: "PP67",
    totalTested: 220,
    correctlyDefined: 220,
    tradable: 1,
    directionAccuracy: "1/220",
    magnitudeAccuracy: "1/220",
    strongTradable: 1,
    moderateTradable: 0,
    weakTradable: 0,
  },
  {
    testName: "TEST 1",
    periods: '["2024-04","2025-03"],["2025-04","2025-09"]',
    set: "PC_SC",
    code: "PC-SC-D-M3-E02-PP67",
    datasetType: "PC",
    consistency: "SC",
    verifySignal: "D",
    magnitude: "M3",
    effectSize: "E02",
    passPercentage: "PP67",
    totalTested: 220,
    correctlyDefined: 220,
    tradable: 1,
    directionAccuracy: "1/220",
    magnitudeAccuracy: "1/220",
    strongTradable: 0,
    moderateTradable: 0,
    weakTradable: 1,
  },
  // TEST 1 - PC_CC
  {
    testName: "TEST 1",
    periods: '["2024-04","2025-03"],["2025-04","2025-09"]',
    set: "PC_CC",
    code: "PC-CC-DC-M3-E02-PP67",
    datasetType: "PC",
    consistency: "CC",
    verifySignal: "DC",
    magnitude: "M3",
    effectSize: "E02",
    passPercentage: "PP67",
    totalTested: 228,
    correctlyDefined: 221,
    tradable: 1,
    directionAccuracy: "47/221",
    magnitudeAccuracy: "1/221",
    strongTradable: 0,
    moderateTradable: 0,
    weakTradable: 1,
  },
  {
    testName: "TEST 1",
    periods: '["2024-04","2025-03"],["2025-04","2025-09"]',
    set: "PC_CC",
    code: "PC-CC-D-M3-E02-PP67",
    datasetType: "PC",
    consistency: "CC",
    verifySignal: "D",
    magnitude: "M3",
    effectSize: "E02",
    passPercentage: "PP67",
    totalTested: 228,
    correctlyDefined: 228,
    tradable: 1,
    directionAccuracy: "51/228",
    magnitudeAccuracy: "1/228",
    strongTradable: 0,
    moderateTradable: 0,
    weakTradable: 1,
  },
  // TEST 1 - BP
  {
    testName: "TEST 1",
    periods: '["2024-04","2025-03"],["2025-04","2025-09"]',
    set: "BP",
    code: "BP-DC-M3-PP67",
    datasetType: "BP",
    consistency: "null",
    verifySignal: "DC",
    magnitude: "M3",
    effectSize: "null",
    passPercentage: "PP67",
    totalTested: 63,
    correctlyDefined: 55,
    tradable: 0,
    directionAccuracy: "39/55",
    magnitudeAccuracy: "0/55",
    strongTradable: 0,
    moderateTradable: 0,
    weakTradable: 0,
  },
  {
    testName: "TEST 1",
    periods: '["2024-04","2025-03"],["2025-04","2025-09"]',
    set: "BP",
    code: "BP-D-M3-PP67",
    datasetType: "BP",
    consistency: "null",
    verifySignal: "D",
    magnitude: "M3",
    effectSize: "null",
    passPercentage: "PP67",
    totalTested: 63,
    correctlyDefined: 63,
    tradable: 0,
    directionAccuracy: "45/63",
    magnitudeAccuracy: "0/63",
    strongTradable: 0,
    moderateTradable: 0,
    weakTradable: 0,
  },
  // TEST 2 - PC_SC
  {
    testName: "TEST 2",
    periods: '["2025-01","2025-06"],["2025-07","2025-09"]',
    set: "PC_SC",
    code: "PC-SC-DC-M3-E02-PP67",
    datasetType: "PC",
    consistency: "SC",
    verifySignal: "DC",
    magnitude: "M3",
    effectSize: "E02",
    passPercentage: "PP67",
    totalTested: 597,
    correctlyDefined: 597,
    tradable: 5,
    directionAccuracy: "269/597",
    magnitudeAccuracy: "5/597",
    strongTradable: 0,
    moderateTradable: 3,
    weakTradable: 2,
  },
  {
    testName: "TEST 2",
    periods: '["2025-01","2025-06"],["2025-07","2025-09"]',
    set: "PC_SC",
    code: "PC-SC-D-M3-E02-PP67",
    datasetType: "PC",
    consistency: "SC",
    verifySignal: "D",
    magnitude: "M3",
    effectSize: "E02",
    passPercentage: "PP67",
    totalTested: 597,
    correctlyDefined: 597,
    tradable: 5,
    directionAccuracy: "269/597",
    magnitudeAccuracy: "5/597",
    strongTradable: 0,
    moderateTradable: 3,
    weakTradable: 2,
  },
  // TEST 2 - PC_CC
  {
    testName: "TEST 2",
    periods: '["2025-01","2025-06"],["2025-07","2025-09"]',
    set: "PC_CC",
    code: "PC-CC-DC-M3-E02-PP67",
    datasetType: "PC",
    consistency: "CC",
    verifySignal: "DC",
    magnitude: "M3",
    effectSize: "E02",
    passPercentage: "PP67",
    totalTested: 571,
    correctlyDefined: 542,
    tradable: 8,
    directionAccuracy: "247/542",
    magnitudeAccuracy: "8/542",
    strongTradable: 1,
    moderateTradable: 3,
    weakTradable: 4,
  },
  {
    testName: "TEST 2",
    periods: '["2025-01","2025-06"],["2025-07","2025-09"]',
    set: "PC_CC",
    code: "PC-CC-D-M3-E02-PP67",
    datasetType: "PC",
    consistency: "CC",
    verifySignal: "D",
    magnitude: "M3",
    effectSize: "E02",
    passPercentage: "PP67",
    totalTested: 571,
    correctlyDefined: 571,
    tradable: 8,
    directionAccuracy: "254/571",
    magnitudeAccuracy: "8/571",
    strongTradable: 1,
    moderateTradable: 3,
    weakTradable: 4,
  },
  // TEST 2 - BP
  {
    testName: "TEST 2",
    periods: '["2025-01","2025-06"],["2025-07","2025-09"]',
    set: "BP",
    code: "BP-DC-M3-PP67",
    datasetType: "BP",
    consistency: "null",
    verifySignal: "DC",
    magnitude: "M3",
    effectSize: "null",
    passPercentage: "PP67",
    totalTested: 362,
    correctlyDefined: 302,
    tradable: 26,
    directionAccuracy: "170/302",
    magnitudeAccuracy: "26/302",
    strongTradable: 2,
    moderateTradable: 13,
    weakTradable: 11,
  },
  {
    testName: "TEST 2",
    periods: '["2025-01","2025-06"],["2025-07","2025-09"]',
    set: "BP",
    code: "BP-D-M3-PP67",
    datasetType: "BP",
    consistency: "null",
    verifySignal: "D",
    magnitude: "M3",
    effectSize: "null",
    passPercentage: "PP67",
    totalTested: 362,
    correctlyDefined: 362,
    tradable: 30,
    directionAccuracy: "198/362",
    magnitudeAccuracy: "30/362",
    strongTradable: 3,
    moderateTradable: 16,
    weakTradable: 11,
  },
];
